name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installing Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libffi libgit2 pkg-config meson ninja 
    - name: Installing Testing Framework
      run: |
        git clone https://github.com/Snaipe/Criterion.git
        meson install -C build
        ldconfig
    - uses: actions/checkout@v3
    - name: Creating binary executable
      run: make clean all
    - name: Running Criterion Tests
      run: ./bin/proxy_tests --verbose
